#!/bin/bash

sudo apt-get install -y build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git python python-zmq zlib1g-dev wget libcurl4-openssl-dev bsdmainutils automake curl
#rm -rf .komodo
rm -rf komodo
cd ~/
git clone https://github.com/jl777/komodo
cd ~/komodo
git checkout dev
./zcutil/fetch-params.sh
./zcutil/build.sh -j2
mkdir ~/.komodo
echo "server=1" >> ~/.komodo/komodo.conf
echo "listen=1" >> ~/.komodo/komodo.conf
echo "rpcuser=`head -c 32 /dev/urandom | base64`" >> ~/.komodo/komodo.conf
echo "rpcpassword=`head -c 32 /dev/urandom | base64`" >> ~/.komodo/komodo.conf
cd ~/komodo/src

##Uncomment in case you want to run komodo blockchain.
#./komodod -daemon 

## Uncomment and adapt if you want to run your own blockchain blockchain
#./komodod -ac_name=EQL -ac_supply=500000000 -addnode=46.101.124.153 -daemon
