#!/bin/bash 


cd ~/komodo/src
bet=$(./komodo-cli -ac_name=KMDICE dicebet KMDICE 5be49570c56d036abb08b6d084da93a8a86f58fc48db4a1086be95540d752d6f  $1 $2)
bet_hex=$(echo $bet | jq -r '.hex')
bet_txid=$(komodo-cli -ac_name=KMDICE sendrawtransaction $bet_hex)
echo $bet_txid
sleep 10
bet_status=$(komodo-cli -ac_name=KMDICE dicestatus KMDICE 5be49570c56d036abb08b6d084da93a8a86f58fc48db4a1086be95540d752d6f $bet_txid)
echo $bet_status
