#!/bin/bash 
figlet "KMDICE"

cd ~/komodo/src
getinfo=$(./komodo-cli -ac_name=KMDICE getinfo)
balance=$(echo $getinfo | jq -r '.balance')
echo 'Wallet balance:' $balance
bet=$(./komodo-cli -ac_name=KMDICE dicebet KMDICE 5be49570c56d036abb08b6d084da93a8a86f58fc48db4a1086be95540d752d6f  $1 $2)
bet_hex=$(echo $bet | jq -r '.hex')
bet_txid=$(./komodo-cli -ac_name=KMDICE sendrawtransaction $bet_hex)
echo $bet_txid
echo "$bet_txid" > ~/bettxid.txt
echo "Waiting bet tx to confirm"
sleep 20
bet_status=$(komodo-cli -ac_name=KMDICE dicestatus KMDICE 5be49570c56d036abb08b6d084da93a8a86f58fc48db4a1086be95540d752d6f $bet_txid)
betStatus_result=$(echo $bet_status | jq -r '.status')
betAmount_result=$(echo $bet_status | jq -r '.won')
if [ "$betAmount_result" != "null" ]; then figlet $betAmount_result
fi
figlet $betStatus_result


